[data.top_pypi_packages]
last_30_days = { repo = "hugovk/top-pypi-packages", path = "top-pypi-packages-30-days.min.json", csv = "top-pypi-packages-30-days.csv" }

[data.pypi_metadata]
semvec = { hf_path = "hf://datasets/semvec/pypi-packages/packages_data/*.parquet", output = "repo_urls.parquet" }
