[data.top_pypi_packages]
last_30_days = { repo = "hugovk/top-pypi-packages", path = "top-pypi-packages-30-days.min.json", csv = "top-pypi-packages-30-days.csv" }

[data.pypi_metadata]
semvec = { hf_path = "hf://datasets/semvec/pypi-packages/packages_data/*.parquet", output = "repo_urls.parquet" }

[data.workflows]
default = { source = "repo_urls.parquet", repos_dir = "workflows/repos", packages_dir = "workflows/packages" }

[data.results]
default = { packages_dir = "workflows/packages", tp_dir = "results/tp", notp_dir = "results/notp", unk_dir = "results/unk" }

[data.results_nogithub]
default = { tp_dir = "results_nogithub/tp", notp_dir = "results_nogithub/notp", unk_dir = "results_nogithub/unk" }

[data.report]
default = { source = "repo_urls.parquet", output = "report.tsv" }

[data.analysis]
default = { report_mini = "report_mini.tsv", parquet = "repo_urls.parquet", downloads = "top-pypi-packages-30-days.csv", output_dir = "analysis" }

[data.tracker]
default = { source = "repo_urls.parquet", report = "report_mini.tsv", repos_dir = "tracker/repos", packages_dir = "tracker/packages", keywords = ["trusted publishing", "trusted publisher", "OIDC publish"] }
